language: csharp
os:
  - osx
  - linux

# Ubuntu 14.04
sudo: required
dist: trusty

# OS X 10.12
osx_image: xcode9.2

mono:
  - latest

dotnet: 2.2.100

before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb

  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.2

  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script:
  - ./build.sh --verbosity diagnostic

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine

notifications:
  email:
    recipients:
      - wangtianjiao.wang959@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
