language: csharp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      mono: latest
      dotnet: 2.2.100

    - os: osx
      osx_image: xcode10.1
      mono: latest
      dotnet: 2.2.100

    - os: windows
      mono: none
      dotnet: 2.2.100

before_install:

  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script:
  - ./build.sh --verbosity diagnostic

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine

notifications:
  email:
    recipients:
      - wangtianjiao.wang959@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
