# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- azure-pipelines

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      echo hello from Linux
      mono --version
      dotnet --info
      ./build.sh

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      echo hello from macOS
      mono --version
      dotnet --info
      ./build.sh

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      echo hello from Windows
      dotnet --info
      choco install nuget.commandline
      powershell Get-ExecutionPolicy -List
      powershell .\build.ps1