
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~P:dnlib.DotNet.ModuleDef.IsClr20")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~P:dnlib.DotNet.ModuleDef.IsClr40")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~P:dnlib.DotNet.ModuleDef.IsClr10")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~P:dnlib.DotNet.ModuleDef.IsClr11")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.MD.ENCMetadata.GetEventRidList(System.UInt32)~dnlib.DotNet.MD.RidList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.MD.ENCMetadata.GetPropertyRidList(System.UInt32)~dnlib.DotNet.MD.RidList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.MD.ENCMetadata.GetMethodRidList(System.UInt32)~dnlib.DotNet.MD.RidList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.MD.ENCMetadata.GetTypeDefRidList~dnlib.DotNet.MD.RidList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.MD.ENCMetadata.GetExportedTypeRidList~dnlib.DotNet.MD.RidList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.MD.ENCMetadata.GetFieldRidList(System.UInt32)~dnlib.DotNet.MD.RidList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.AssemblyResolver.GetPrivatePaths(System.String,System.String)~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.SigComparer.IsFnPtrElementType(System.Type)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.Utils.LocaleCompareTo(dnlib.DotNet.UTF8String,dnlib.DotNet.UTF8String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.Utils.LocaleCompareTo(dnlib.DotNet.UTF8String,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.EndsWith(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.StartsWith(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.CompareTo(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.IndexOf(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.IndexOf(System.String,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.IndexOf(System.String,System.Int32,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.LastIndexOf(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.LastIndexOf(System.String,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.UTF8String.LastIndexOf(System.String,System.Int32,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.W32Resources.ResourceName.CompareTo(dnlib.W32Resources.ResourceName)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.Writer.Win32ResourcesChunk.WriteTo(dnlib.DotNet.Writer.DataWriter,dnlib.W32Resources.ResourceDirectory)~System.UInt32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.ReflectionExtensions.IsSZArray(System.Type)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:dnlib.DotNet.Pdb.WindowsPdb.PdbCustomDebugInfoReader.GetNestedType(System.String)~dnlib.DotNet.TypeDef")]

